function init(self)
self.speed = 540
end

function update(self, dt)
	local pos = go.get_position()
	if pos.x < -500 then
		msg.post("/level/controller#controller", "delete_spawn", { id = go.get_id() })
	end
	pos.x = pos.x - self.speed * dt
	go.set_position(pos)
end



function on_message(self, message_id, message, sender)
	if message_id == hash('set-speed') then
		self.speed = message.speed
	end
end

function on_input(self, action_id, action)

end

